services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Map the container port to the host port
    env_file:
      - project.env  # Load environment variables from .env file
    volumes:
      - ./backend:/app  # Mount the backend code for development
      - /app/node_modules  # Omit node_modules from mounting
    command: ["npx", "nodemon", "src/utils/index.ts"]  # Use npx to run nodemon

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"  # Map the frontend port to the host port
    volumes:
      - ./frontend:/app  # Mount the frontend code for development
      # - /app/node_modules  # Omit node_modules from mounting

volumes:
  pgdata: